<?php
 define('SYSTEM_PATH', 'system');
 define('CONTROLLER', 'controller');
 define('MODEL', 'model');
 define('VIEW', 'view');
 define('TEMPLATE_PATH', 'templates');
 define('JS', 'js');
 define('CSS', 'css');
 define('IMG', 'img');
 define('LIBRARIES', 'libraries');
 define('HELPERS_PATH', 'helpers');
 define('TPL', '.tpl');
 define('HTML', '.html');
 define('MODULES', 'modules');
 define('DEBUG', FALSE );
 define('ERRORS', FALSE);
 define('DS', DIRECTORY_SEPARATOR);
 define('FULL_SITE', '#######');
 define('SITE_URL', '#######');
 define('CATEGORY', 'category');
 define('PRODUCT', 'product');
 define('ARTICLE', 'article');
 define('ITEM_TO_CATEGORY', 15);